// <auto-generated />
namespace CheapDeal.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddPaymentDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPaymentDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202602050701213_AddPaymentDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
